import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Enzo Campos",
  description: "Generated by create next app",
};

import { JetBrains_Mono } from "next/font/google";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // escolha os pesos desejados
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={jetbrainsMono.className}
      >
        {children}
      </body>
    </html>
  );
}
